CREATE TABLE IF NOT EXISTS site_content (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT DEFAULT (datetime('now'))
);

INSERT OR REPLACE INTO site_content (key, value) VALUES
('profile', '{"name":"Khun Thaw Zin Htun","title":"IT Infrastructure Engineer","tagline":"I keep networks running and build the automation around them.","location":"Yangon, Myanmar","email":"hello@example.com","github":"","telegram":""}'),
('about', '{"heading":"About","body":"I work in IT infrastructure. My background is in NOC operations, where I handled monitoring, ticketing, and SLA reporting.\n\nOver time I automated most of the repetitive parts. Ticket logs flow into timesheets on their own. SLA numbers get calculated without spreadsheets. Alerts reach the team over Telegram before anyone has to ask.\n\nI also work with AI agents now. I run my own MCP server, build custom agent skills, and route work across different models depending on the job.\n\nI am currently looking for infrastructure and automation work."}'),
('skills', '{"categories":[{"name":"Infrastructure and Networking","items":["Cloudflare Zero Trust and tunnels","FortiGate firewalls","Zabbix monitoring","Tailscale and VPN mesh","DNS and network diagnostics"]},{"name":"Automation and Scripting","items":["Python","PowerShell","n8n workflows","JSON and Excel pipelines","Windows services"]},{"name":"AI and Agents","items":["Google Antigravity","Claude Code","MCP server design","Multi-agent setups","Prompt engineering"]},{"name":"Data","items":["BigQuery and SQL","Redmine API","SLA reporting","Excel automation"]}]}'),
('projects', '[{"title":"WinMCP","description":"A Windows service that lets AI agents run tasks on the machine through the MCP protocol. It stays up around the clock and is reachable remotely through a Cloudflare tunnel.","tech":["Python","MCP","Cloudflare Tunnel","C#"],"link":""},{"title":"Working Hours Automation","description":"Takes ticket logs from Redmine and turns them into timesheets. Runs every day without anyone touching it.","tech":["Python","PowerShell","Excel"],"link":""},{"title":"SLA Reporter","description":"Checks support tickets against SLA targets and produces the numbers. No spreadsheets involved.","tech":["Python","Redmine"],"link":""},{"title":"Telegram Alert Bot","description":"Watches the ticket queue and sends SLA alerts to Telegram as they happen.","tech":["Python","Telegram API"],"link":""},{"title":"Veil Reader","description":"A private Android app for reading manga. Fullscreen pages, volume keys turn the pages, and reading history never leaves the device.","tech":["Kotlin","Android"],"link":""}]'),
('experience', '[{"role":"IT Service Technician, Infrastructure and NOC","org":"","period":"Until October 2026","points":["Handled monitoring, ticketing, and SLA compliance for infrastructure operations.","Built automation connecting Redmine, timesheets, and alerting.","Managed Cloudflare tunnels, FortiGate firewalls, and Zabbix monitoring."]}]'),
('contact', '{"heading":"Contact","text":"I am currently open to infrastructure and automation work. The fastest way to reach me is email.","email":"hello@example.com"}');
