CREATE TABLE IF NOT EXISTS site_content (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT DEFAULT (datetime('now'))
);

INSERT OR REPLACE INTO site_content (key, value) VALUES
('profile', '{"name":"Khun Thaw Zin Htun","title":"IT Infrastructure Specialist","tagline":"I build my own tools and take on client work.","location":"Yangon, Myanmar","email":"hello@example.com","github":"","telegram":""}'),
('about', '{"heading":"About","body":"I work in IT infrastructure. I spent my working years in a NOC, keeping systems up and automating the repetitive parts. Monitoring, ticketing, SLA reports.\n\nNow I build software a different way. I design the tool, direct AI assistants to build it, test every part myself, and ship it. This site and the Android app in my projects were both built that way.\n\nI take on infrastructure and automation work."}'),
('skills', '{"categories":[{"name":"Infrastructure","items":["NOC monitoring","Windows infrastructure","Network diagnostics","Redmine ticketing"]},{"name":"Automation","items":["Python","PowerShell","n8n workflows","Excel pipelines"]},{"name":"AI-assisted development","items":["Directing AI coding agents","Cloudflare (Tunnels, Pages, Workers, D1)","MCP servers","Shipping Android apps"]}]}'),
('projects', '[{"title":"Veil Reader","description":"A private Android reader for manga and manhwa. History, bookmarks, and reading progress stay on the phone and nowhere else. Tracker blocking, HTTPS-only browsing, and volume keys turn the pages.","tech":["Android","Kotlin","Privacy"],"link":""},{"title":"Nazarick Bridge","description":"My own server that lets AI assistants run tasks on my Windows machine. A local daemon does the work, a Cloudflare tunnel carries it out, and a health check proves it is alive.","tech":["Python","MCP","Cloudflare Tunnel"],"link":""},{"title":"SLA Tracker","description":"A tool from my time in infrastructure support. It reads support tickets, checks them against response targets, and flags the ones about to break. No more surprises in the morning report.","tech":["Python","Redmine","Automation"],"link":""},{"title":"Hours Exporter","description":"Another one from support days. It pulls logged hours out of tickets and builds the weekly timesheet. A chore that took an afternoon now takes one click.","tech":["Python","PowerShell","Excel"],"link":""}]'),
('experience', '[{"role":"IT Service Technician, Infrastructure and NOC","org":"","period":"Until October 2026","points":["Ran monitoring and ticketing for company infrastructure.","Built automation for SLA tracking and timesheets."]}]'),
('contact', '{"heading":"Contact","text":"I am currently open to infrastructure and automation work. The fastest way to reach me is email.","email":"hello@example.com"}');
