CREATE TABLE IF NOT EXISTS site_content (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT DEFAULT (datetime('now'))
);

INSERT OR REPLACE INTO site_content (key, value) VALUES
('profile', '{"name":"Khun Thaw Zin Htun","title":"IT Infrastructure Engineer","tagline":"Infrastructure, automation, and AI tooling for small businesses.","location":"Yangon, Myanmar","email":"khunthawzinhtun.workspace@gmail.com","github":"","telegram":""}'),
('about', '{"heading":"About","body":"I am an IT infrastructure engineer. From 2024 to 2026 I worked as a help desk and service technician at a systems integrator, handling 4,000 tickets across L1, L2, and L3. The work that defines me is what I built.\n\nI migrated the company Redmine from version 4 to 6 across servers with 4 hours of downtime and zero data loss. I built a working hours platform in PHP with role-based access, analytics, and Docker deployment. I run a production monitoring stack on Grafana and Loki. I build AI agents that manage infrastructure, including one that heals network faults on its own.\n\nNow I work for myself. Infrastructure and automation for small businesses, AI-assisted builds, and portfolio sites like this one."}'),
('skills', '{"categories":[{"name":"Infrastructure","items":["FortiGate firewalls and routers","Cisco switches","Aruba, UniFi and Meraki wireless","HIKVISION NVR and CCTV","Dell servers","VMware ESXi (6 hosts, 30 VMs)"]},{"name":"Platforms and DevOps","items":["Docker and Compose","Grafana, Loki and Promtail","PHP and MariaDB","n8n automation","Nginx reverse proxy","Cloudflare (Tunnels, Pages, D1)"]},{"name":"AI-assisted development","items":["AI agents for infrastructure","MCP servers","Python and PowerShell","Shipping Android apps","Portfolio and business sites"]}]}'),
('projects', '[{"title":"Working Hours Platform","description":"A complete working hours and task management platform in PHP. Role-based access for admins, semi-admins, and members, analytics dashboards, audit logging, and Docker deployment. Built for the whole company staff.","tech":["PHP","MariaDB","Docker"],"link":""},{"title":"Infrastructure Monitoring","description":"A production monitoring stack on my own domain. Grafana dashboards, Loki log aggregation, and Promtail collectors, all running in Docker with health checks and persistent storage.","tech":["Grafana","Loki","Docker"],"link":""},{"title":"Nazarick Bridge","description":"An MCP server daemon that gives AI assistants authenticated remote control over infrastructure servers. System telemetry, remote command execution, and service management, reachable through a Cloudflare tunnel.","tech":["Python","MCP","Cloudflare Tunnel"],"link":""},{"title":"Connection Guard","description":"A self-healing network guard. It probes connectivity every 15 seconds, and when the link drops, a tuned model triggers a bounded repair through NetworkManager. Every repair is logged and every action is sandboxed.","tech":["Python","systemd","Machine learning"],"link":""},{"title":"Redmine Migration","description":"Our ticketing system ran Redmine 4 on CentOS 7, which the latest Redmine no longer supports. I set up a new CentOS 10 server, installed Redmine 6, and migrated every ticket and record. 4 hours of downtime, zero data loss.","tech":["Redmine","CentOS","Data migration"],"link":""},{"title":"Veil Reader","description":"A private Android reader for manga and manhwa. History, bookmarks, and reading progress stay on the phone and nowhere else. Tracker blocking, HTTPS-only browsing, and volume keys turn the pages.","tech":["Android","Kotlin","Privacy"],"link":""}]'),
('experience', '[{"role":"Independent IT Engineer","org":"Self-employed","period":"2026 - Present","points":["Infrastructure and automation for small businesses.","Production monitoring stacks, AI infrastructure agents, and portfolio sites."]},{"role":"IT Help Desk and Service Technician","org":"Systems integrator","period":"2024 - 2026","points":["Handled 4,000 support tickets across L1, L2, and L3 over two years.","Migrated Redmine 4 on CentOS 7 to Redmine 6 on CentOS 10 with 4 hours of downtime and zero data loss.","Built the company working hours platform with PHP, role-based access, analytics, and Docker deployment.","Built the company corporate website.","Managed FortiGate firewalls and routers, Cisco switches, Aruba, UniFi and Meraki wireless, HIKVISION CCTV, and 6 ESXi hosts running 30 VMs."]}]'),
('contact', '{"heading":"Contact","text":"I do infrastructure and automation for small businesses, AI-assisted builds, and portfolio sites like this one. Email is the fastest way to reach me.","email":"khunthawzinhtun.workspace@gmail.com"}');
